"""Export data stories to various formats."""

from __future__ import annotations

import json
from typing import Any

from datalens_ai.core.models import DataStory


def story_to_dict(story: DataStory) -> dict[str, Any]:
    """Convert a DataStory to a serializable dict."""
    return {
        "id": story.id,
        "title": story.title,
        "dataset": story.dataset_name,
        "created_at": story.created_at.isoformat(),
        "sections": [
            {
                "title": s.title,
                "narrative": s.narrative,
                "has_chart": s.chart_config is not None,
                "row_count": (
                    s.query_result.row_count if s.query_result else 0
                ),
                "sql": s.query_result.sql_query if s.query_result else "",
            }
            for s in story.sections
        ],
    }


def story_to_json(story: DataStory, indent: int = 2) -> str:
    """Export a DataStory to JSON."""
    return json.dumps(story_to_dict(story), indent=indent)


def story_to_markdown(story: DataStory) -> str:
    """Export a DataStory to Markdown."""
    lines: list[str] = []
    lines.append(f"# {story.title}")
    lines.append("")
    lines.append(f"**Dataset:** {story.dataset_name}")
    lines.append(f"**Generated:** {story.created_at.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")
    lines.append("---")
    lines.append("")

    for i, section in enumerate(story.sections, 1):
        lines.append(f"## {i}. {section.title}")
        lines.append("")

        if section.narrative:
            lines.append(section.narrative)
            lines.append("")

        if section.query_result:
            qr = section.query_result
            if qr.sql_query:
                lines.append("```sql")
                lines.append(qr.sql_query)
                lines.append("```")
                lines.append("")

            if qr.data:
                # Render a simple markdown table (first 10 rows)
                cols = qr.columns
                lines.append("| " + " | ".join(cols) + " |")
                lines.append("| " + " | ".join(["---"] * len(cols)) + " |")
                for row in qr.data[:10]:
                    vals = [str(row.get(c, "")) for c in cols]
                    lines.append("| " + " | ".join(vals) + " |")
                lines.append("")

                if qr.row_count > 10:
                    lines.append(
                        f"*Showing 10 of {qr.row_count} rows.*"
                    )
                    lines.append("")

        lines.append("---")
        lines.append("")

    lines.append(
        "*Generated by [DataLens AI](https://github.com/mekala27-45/datalens-ai)*"
    )
    return "\n".join(lines)
