"""Generate HTML reports from data stories and query results."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from datalens_ai.core.models import DataProfile, DataStory, QueryResult

_CSS = (  # noqa: E501
    "<style>\n"
    "  :root{--primary:#6366F1;--bg:#0F172A;--card:#1E293B;"
    "--text:#F1F5F9;--muted:#94A3B8}\n"
    "  *{box-sizing:border-box;margin:0;padding:0}\n"
    "  body{font-family:'Inter',sans-serif;background:var(--bg);"
    "color:var(--text);padding:40px;line-height:1.6}\n"
    "  .container{max-width:1100px;margin:0 auto}\n"
    "  h1{font-size:2rem;margin-bottom:8px;"
    "background:linear-gradient(135deg,#6366F1,#8B5CF6,#EC4899);"
    "-webkit-background-clip:text;"
    "-webkit-text-fill-color:transparent}\n"
    "  h2{font-size:1.3rem;color:var(--primary);"
    "margin:32px 0 12px}\n"
    "  .meta{color:var(--muted);font-size:.85rem;"
    "margin-bottom:24px}\n"
    "  .card{background:var(--card);"
    "border:1px solid rgba(99,102,241,.2);"
    "border-radius:12px;padding:24px;margin-bottom:20px}\n"
    "  .stats-grid{display:grid;"
    "grid-template-columns:repeat(auto-fit,minmax(200px,1fr));"
    "gap:16px;margin-bottom:24px}\n"
    "  .stat{background:var(--card);"
    "border:1px solid rgba(99,102,241,.15);"
    "border-radius:10px;padding:16px;text-align:center}\n"
    "  .stat-value{font-size:1.8rem;font-weight:700;"
    "color:var(--primary)}\n"
    "  .stat-label{font-size:.85rem;color:var(--muted);"
    "margin-top:4px}\n"
    "  table{width:100%;border-collapse:collapse;"
    "font-size:.9rem;margin:12px 0}\n"
    "  th{background:var(--primary);color:#fff;"
    "padding:10px 12px;text-align:left;font-weight:600}\n"
    "  td{padding:8px 12px;"
    "border-bottom:1px solid rgba(99,102,241,.1)}\n"
    "  tr:hover td{background:rgba(99,102,241,.05)}\n"
    "  code{background:rgba(99,102,241,.15);padding:2px 6px;"
    "border-radius:4px;font-size:.85rem}\n"
    "  pre{background:rgba(15,23,42,.8);"
    "border:1px solid rgba(99,102,241,.2);"
    "border-radius:8px;padding:16px;"
    "overflow-x:auto;font-size:.85rem;margin:12px 0}\n"
    "  .insight{padding:8px 12px;"
    "border-left:3px solid var(--primary);margin:8px 0;"
    "background:rgba(99,102,241,.05);"
    "border-radius:0 8px 8px 0}\n"
    "  .footer{text-align:center;color:var(--muted);"
    "font-size:.8rem;margin-top:40px;padding-top:20px;"
    "border-top:1px solid rgba(99,102,241,.1)}\n"
    "  .badge{display:inline-block;background:var(--primary);"
    "color:#fff;padding:2px 8px;border-radius:4px;"
    "font-size:.75rem;font-weight:600}\n"
    "</style>\n"
)


def generate_html_report(
    story: DataStory | None = None,
    profile: DataProfile | None = None,
    results: list[QueryResult] | None = None,
    title: str = "DataLens AI Report",
) -> str:
    """Generate a complete HTML report."""
    parts: list[str] = []
    parts.append("<!DOCTYPE html>")
    parts.append('<html lang="en"><head>')
    parts.append('<meta charset="UTF-8">')
    parts.append(f"<title>{_esc(title)}</title>")
    parts.append(_CSS)
    parts.append("</head><body>")
    parts.append('<div class="container">')

    # Header
    parts.append(f"<h1>{_esc(title)}</h1>")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    parts.append(f'<p class="meta">Generated {now} by DataLens AI</p>')

    # Profile section
    if profile:
        parts.append(_render_profile(profile))

    # Story sections
    if story:
        for i, section in enumerate(story.sections, 1):
            parts.append(_render_story_section(i, section))

    # Standalone query results
    if results:
        parts.append("<h2>Query Results</h2>")
        for result in results:
            parts.append(_render_query_result(result))

    # Footer
    parts.append('<div class="footer">')
    parts.append("Generated by DataLens AI &mdash; AI-Powered Data Analytics")
    parts.append("</div>")

    parts.append("</div></body></html>")
    return "\n".join(parts)


def _render_profile(profile: DataProfile) -> str:
    """Render a data profile section."""
    lines: list[str] = []
    lines.append("<h2>Dataset Profile</h2>")
    lines.append('<div class="stats-grid">')
    lines.append(_stat_card(str(profile.row_count), "Rows"))
    lines.append(_stat_card(str(profile.column_count), "Columns"))
    lines.append(_stat_card(f"{profile.quality_score:.0f}/100", "Quality Score"))
    lines.append(
        _stat_card(str(len(profile.quality_issues)), "Issues Found")
    )
    lines.append("</div>")

    # Column summary table
    lines.append('<div class="card">')
    lines.append("<h2>Column Summary</h2>")
    lines.append("<table>")
    lines.append("<tr><th>Column</th><th>Type</th><th>Unique</th>"
                 "<th>Nulls</th><th>Semantic</th></tr>")
    for col in profile.columns:
        sem = col.semantic_type or "—"
        lines.append(
            f"<tr><td><code>{_esc(col.name)}</code></td>"
            f"<td>{_esc(col.dtype)}</td>"
            f"<td>{col.unique_count}</td>"
            f"<td>{col.null_pct:.1%}</td>"
            f'<td><span class="badge">{_esc(sem)}</span></td></tr>'
        )
    lines.append("</table></div>")

    return "\n".join(lines)


def _render_story_section(idx: int, section: Any) -> str:
    """Render a single story section."""
    lines: list[str] = []
    lines.append(f"<h2>{idx}. {_esc(section.title)}</h2>")
    lines.append('<div class="card">')

    if section.narrative:
        for para in section.narrative.split("\n\n"):
            if para.strip():
                lines.append(f"<p>{_esc(para.strip())}</p>")

    if section.query_result:
        lines.append(_render_query_result(section.query_result))

    lines.append("</div>")
    return "\n".join(lines)


def _render_query_result(result: QueryResult) -> str:
    """Render a query result with SQL and data table."""
    lines: list[str] = []

    if result.sql_query:
        lines.append(f"<pre>{_esc(result.sql_query)}</pre>")

    if result.insights:
        for insight in result.insights[:4]:
            lines.append(f'<div class="insight">{_esc(insight)}</div>')

    if result.data:
        lines.append("<table>")
        lines.append(
            "<tr>" + "".join(f"<th>{_esc(c)}</th>" for c in result.columns) + "</tr>"
        )
        for row in result.data[:50]:
            cells = "".join(
                f"<td>{_esc(str(row.get(c, '')))}</td>"
                for c in result.columns
            )
            lines.append(f"<tr>{cells}</tr>")
        lines.append("</table>")

        if result.row_count > 50:
            lines.append(
                f'<p class="meta">Showing 50 of {result.row_count} rows</p>'
            )

    return "\n".join(lines)


def _stat_card(value: str, label: str) -> str:
    return (
        f'<div class="stat">'
        f'<div class="stat-value">{_esc(value)}</div>'
        f'<div class="stat-label">{_esc(label)}</div>'
        f"</div>"
    )


def _esc(text: str) -> str:
    """Escape HTML entities."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
