"""Generate Markdown reports from data stories and profiles."""

from __future__ import annotations

from datetime import datetime, timezone

from datalens_ai.core.models import DataProfile, DataStory, QueryResult


def generate_markdown_report(
    story: DataStory | None = None,
    profile: DataProfile | None = None,
    results: list[QueryResult] | None = None,
    title: str = "DataLens AI Report",
) -> str:
    """Generate a complete Markdown report."""
    lines: list[str] = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"*Generated {now} by DataLens AI*")
    lines.append("")

    if profile:
        lines.append(_render_profile(profile))

    if story:
        for i, section in enumerate(story.sections, 1):
            lines.append(f"## {i}. {section.title}")
            lines.append("")

            if section.narrative:
                lines.append(section.narrative)
                lines.append("")

            if section.query_result:
                lines.append(_render_result(section.query_result))

            lines.append("---")
            lines.append("")

    if results:
        lines.append("## Query Results")
        lines.append("")
        for result in results:
            lines.append(f"### {result.question}")
            lines.append("")
            lines.append(_render_result(result))

    lines.append(
        "*Generated by [DataLens AI]"
        "(https://github.com/mekala27-45/datalens-ai)*"
    )
    return "\n".join(lines)


def _render_profile(profile: DataProfile) -> str:
    """Render data profile as Markdown."""
    lines: list[str] = []
    lines.append("## Dataset Profile")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Rows | {profile.row_count:,} |")
    lines.append(f"| Columns | {profile.column_count} |")
    lines.append(f"| Quality Score | {profile.quality_score:.0f}/100 |")
    lines.append(f"| Issues | {len(profile.quality_issues)} |")
    lines.append("")

    lines.append("### Columns")
    lines.append("")
    lines.append("| Column | Type | Unique | Nulls |")
    lines.append("|--------|------|--------|-------|")
    for col in profile.columns:
        lines.append(
            f"| `{col.name}` | {col.dtype} | {col.unique_count} "
            f"| {col.null_pct:.1%} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def _render_result(result: QueryResult) -> str:
    """Render a single query result as Markdown."""
    lines: list[str] = []

    if result.sql_query:
        lines.append("```sql")
        lines.append(result.sql_query)
        lines.append("```")
        lines.append("")

    if result.insights:
        for insight in result.insights[:4]:
            lines.append(f"- {insight}")
        lines.append("")

    if result.data:
        cols = result.columns
        lines.append("| " + " | ".join(cols) + " |")
        lines.append("| " + " | ".join(["---"] * len(cols)) + " |")
        for row in result.data[:20]:
            vals = [str(row.get(c, "")) for c in cols]
            lines.append("| " + " | ".join(vals) + " |")
        lines.append("")

        if result.row_count > 20:
            lines.append(f"*Showing 20 of {result.row_count} rows.*")
            lines.append("")

    return "\n".join(lines)
